// Code generated by MockGen. DO NOT EDIT.
// Source: ./uuid_service.go

// Package mock_ports is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUUIDService is a mock of UUIDService interface.
type MockUUIDService struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDServiceMockRecorder
}

// MockUUIDServiceMockRecorder is the mock recorder for MockUUIDService.
type MockUUIDServiceMockRecorder struct {
	mock *MockUUIDService
}

// NewMockUUIDService creates a new mock instance.
func NewMockUUIDService(ctrl *gomock.Controller) *MockUUIDService {
	mock := &MockUUIDService{ctrl: ctrl}
	mock.recorder = &MockUUIDServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDService) EXPECT() *MockUUIDServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockUUIDService) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockUUIDServiceMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUUIDService)(nil).Generate))
}
