// Code generated by MockGen. DO NOT EDIT.
// Source: course_repository.go

// Package mock_ports is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/matheusvmallmann/plataforma-ead/service-course/domain/entities"
)

// MockCourseRepository is a mock of CourseRepository interface.
type MockCourseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourseRepositoryMockRecorder
}

// MockCourseRepositoryMockRecorder is the mock recorder for MockCourseRepository.
type MockCourseRepositoryMockRecorder struct {
	mock *MockCourseRepository
}

// NewMockCourseRepository creates a new mock instance.
func NewMockCourseRepository(ctrl *gomock.Controller) *MockCourseRepository {
	mock := &MockCourseRepository{ctrl: ctrl}
	mock.recorder = &MockCourseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseRepository) EXPECT() *MockCourseRepositoryMockRecorder {
	return m.recorder
}

// AddSection mocks base method.
func (m *MockCourseRepository) AddSection(Section *entities.CourseSection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSection", Section)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSection indicates an expected call of AddSection.
func (mr *MockCourseRepositoryMockRecorder) AddSection(Section interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSection", reflect.TypeOf((*MockCourseRepository)(nil).AddSection), Section)
}

// Create mocks base method.
func (m *MockCourseRepository) Create(Course *entities.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", Course)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCourseRepositoryMockRecorder) Create(Course interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourseRepository)(nil).Create), Course)
}

// Delete mocks base method.
func (m *MockCourseRepository) Delete(Id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", Id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCourseRepositoryMockRecorder) Delete(Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCourseRepository)(nil).Delete), Id)
}

// FindById mocks base method.
func (m *MockCourseRepository) FindById(Id string) (*entities.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", Id)
	ret0, _ := ret[0].(*entities.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockCourseRepositoryMockRecorder) FindById(Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockCourseRepository)(nil).FindById), Id)
}

// RemoveSection mocks base method.
func (m *MockCourseRepository) RemoveSection(Id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSection", Id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSection indicates an expected call of RemoveSection.
func (mr *MockCourseRepositoryMockRecorder) RemoveSection(Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSection", reflect.TypeOf((*MockCourseRepository)(nil).RemoveSection), Id)
}

// Update mocks base method.
func (m *MockCourseRepository) Update(Course *entities.Course) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", Course)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourseRepositoryMockRecorder) Update(Course interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourseRepository)(nil).Update), Course)
}

// UpdateSection mocks base method.
func (m *MockCourseRepository) UpdateSection(Section *entities.CourseSection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSection", Section)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSection indicates an expected call of UpdateSection.
func (mr *MockCourseRepositoryMockRecorder) UpdateSection(Section interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSection", reflect.TypeOf((*MockCourseRepository)(nil).UpdateSection), Section)
}
