version: "3.9"

services:
  database-prod:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - service-core-backend
    volumes:
      - ./data/service-course-db:/data/db

  backend-prod:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@database-prod:27017
      - POSTGRES_URI=postgresql://postgres:postgres@database-prod:5432/service-core?sslmode=disable
      - RUN_DAEMON=true
      - JWT_SECRET_KEY=teste
    networks:
      - service-core-backend
    volumes:
      - ./videos:/videos

  front-prod:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3000"
    environment:
      - SERVER_HOST=http://backend-prod:3000
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=teste
    networks:
      - service-core-backend

networks:
  service-core-backend:
    driver: "bridge"
