version: "3.9"

services:
  service-course-db:
    image: mongo:latest
    container_name: service-course-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - service-core-backend
    volumes:
      - ./data/service-course-db:/data/db

  service-course:
    container_name: service-course
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@service-course-db:27017
      - POSTGRES_URI=postgresql://postgres:postgres@service-core-db:5432/service-core?sslmode=disable
      - RUN_DAEMON=false
      - JWT_SECRET_KEY=teste
    networks:
      - service-core-backend
    volumes:
      - ./backend:/app
      - ./videos:/videos

  front:
    container_name: front
    build: ./front
    ports:
      - "3002:3000"
    environment:
      - SERVICE_CORE_URL=http://service-core:3000
      - SERVICE_COURSE_URL=service-course:3000
      - JWT_SECRET=teste
      - SERVER_HOST=http://localhost:3000
      - NEXT_PUBLIC_SERVER_HOST=http://localhost:3002
    networks:
      - service-core-backend
    volumes:
      - ./front:/app
      - ./videos:/videos
      - /app/node_modules
      - /app/.next

networks:
  service-core-backend:
    driver: "bridge"
