version: "3.9"

services:
  service-core-db:
    image: postgres:latest
    container_name: service-core-db
    environment:
      POSTGRES_DB: service-core
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - service-core-backend
    volumes:
      - ./data/service-core-db:/var/lib/postgresql/data

  service-core-migrate:
    image: migrate/migrate
    container_name: service-core-migrate
    volumes:
      - ./service-core/migrations:/migrations
    depends_on:
      - service-core-db
    networks:
      - service-core-backend
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@service-core-db:5432/service-core?sslmode=disable",
        "up",
      ]

  service-core:
    container_name: service-core
    build: ./service-core
    ports:
      - "3000:3000"
    depends_on:
      - service-core-db
      - service-core-migrate
    networks:
      - service-core-backend
    volumes:
      - ./service-core:/app

  service-course-db:
    image: mongo:latest
    container_name: service-course-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/service-course-db:/data/db

  service-course:
    container_name: service-course
    build: ./service-course
    ports:
      - "3001:3000"
    networks:
      - service-core-backend
    volumes:
      - ./service-course:/app

networks:
  service-core-backend:
    driver: "bridge"
