version: "3.9"

services:
  service-course-db:
    image: mongo:latest
    container_name: service-course-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - service-core-backend
    volumes:
      - ./data/service-course-db:/data/db

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:example@service-course-db:27017
      - RUN_DAEMON=true
      - JWT_SECRET_KEY=teste
    networks:
      - service-core-backend
    volumes:
      - ./backend:/app
      - ./videos:/videos

  front:
    container_name: front
    build: ./front
    ports:
      - "3002:3000"
    environment:
      - SERVER_HOST=http://backend:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=teste
    networks:
      - service-core-backend
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next

networks:
  service-core-backend:
    driver: "bridge"
