version: "3.9"

services:
  backend-prod:
    container_name: backend
    image: 315655993037.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    ports:
      - "3000:3000"
    env_file:
      - /etc/environment
    networks:
      - plataforma-ead-net
    volumes:
      - ./videos:/videos

  front-prod:
    container_name: front
    image: 315655993037.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    ports:
      - "3002:3000"
    env_file:
      - /etc/environment
    networks:
      - plataforma-ead-net

networks:
  plataforma-ead-net:
    driver: "bridge"
