apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
data:
  MONGODB_URI: "mongodb://root:example@service-course-db:27017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  SERVICE_CORE_URL: "http://service-core:3000"
  SERVICE_COURSE_URL: "http://service-course:3000"
  JWT_SECRET: "89fd6a16-46f2-4213-b3ac-0bf4d0cd45e4"
  SERVER_HOST: "http://service-front:3000"
  NEXT_PUBLIC_SERVER_HOST: "http://aa76ef71902f84c74bd512c0f1d98a27-582466465.us-east-1.elb.amazonaws.com:3001"
