apiVersion: v1
kind: Service
metadata:
  name: service-core
spec:
  selector:
    app: service-core
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-core-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-core
  template:
    metadata:
      labels:
        app: service-core
    spec:
      containers:
        - name: service-core
          image: 315655993037.dkr.ecr.us-east-1.amazonaws.com/service-core-prod:latest

          envFrom:
            - configMapRef:
                name: service-core-env

      imagePullSecrets:
        - name: us-east-1-ecr-registry
