apiVersion: v1
kind: Service
metadata:
  name: service-front
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: 315655993037.dkr.ecr.us-east-1.amazonaws.com/front-prod:latest
          envFrom:
            - configMapRef:
                name: front-env
      imagePullSecrets:
        - name: us-east-1-ecr-registry