# Use a imagem oficial do Node.js como base
FROM node:18-alpine

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos necessários para o diretório de trabalho
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install --omit=dev

# Copie os arquivos do código-fonte para o diretório de trabalho
COPY . .

# Construa a aplicação Next.js
RUN npm run build

# Exponha a porta que a aplicação Next.js estará ouvindo
EXPOSE 3000

# Inicie o servidor Next.js
CMD ["npm", "start"]